/*
 * This source file was generated by the Gradle 'init' task
 */
package com.skapadia.akka.streams

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class StreamAppSuite extends AnyFunSuite {
  test("someLibraryMethod is always true") {
    def library = new StreamApp()
    assert(library.someLibraryMethod())

  }
}
