/*
 * This source file was generated by the Gradle 'init' task
 */
package com.skapadia.akka.streams

class Library {
  def someLibraryMethod(): Boolean = true
}

object Library{
  def main(args: Array[String]): Unit = {
    println("Hello world!")
  }
}
